name: "Build Prod"

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-prod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Using Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 22.
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run tests
        run: npm run test
  